In [1]:
import pandas as pd

C:\Users\ACS\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df=pd.read_csv(r"C:\Users\ACS\Downloads\swiggy_demographic (1).csv")
df

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,time_taken,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,sunny,high,...,24,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,stormy,jam,...,33,BANG,25,3,friday,0,5.0,19.0,evening,20.183530
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,sandstorms,low,...,26,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,sunny,medium,...,21,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,cloudy,high,...,30,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45497,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,windy,high,...,32,JAP,24,3,thursday,0,10.0,11.0,morning,1.489846
45498,AGRRES16DEL01,21.0,4.6,NaN,NaN,NaN,NaN,2022-02-16,windy,jam,...,36,AGR,16,2,wednesday,0,15.0,19.0,evening,NaN
45499,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,2022-03-11,cloudy,low,...,16,CHEN,11,3,friday,0,15.0,23.0,night,4.657195
45500,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,2022-03-07,cloudy,high,...,26,COIMB,7,3,monday,0,5.0,13.0,afternoon,6.232393
45501,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,2022-03-02,fog,medium,...,36,RANCHI,2,3,wednesday,0,5.0,17.0,evening,12.074396

In [3]:
df.duplicated().sum()

np.int64(0)

In [4]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,45492,45493,45494,45495,45496,45497,45498,45499,45500,45501
rider_id,INDORES13DEL02,BANGRES18DEL02,BANGRES19DEL01,COIMBRES13DEL02,CHENRES12DEL01,HYDRES09DEL03,RANCHIRES15DEL01,MYSRES15DEL02,HYDRES05DEL02,DEHRES17DEL01,...,MYSRES13DEL02,CHENRES08DEL02,KNPRES03DEL01,BANGRES16DEL03,RANCHIRES16DEL01,JAPRES04DEL01,AGRRES16DEL01,CHENRES08DEL03,COIMBRES11DEL01,RANCHIRES09DEL02
age,37.0,34.0,23.0,38.0,32.0,22.0,33.0,35.0,22.0,36.0,...,36.0,37.0,30.0,28.0,35.0,30.0,21.0,30.0,20.0,23.0
ratings,4.9,4.5,4.4,4.7,4.6,4.8,4.7,4.6,4.8,4.2,...,4.8,4.8,4.2,4.9,4.2,4.8,4.6,4.9,4.7,4.9
restaurant_latitude,22.745049,12.913041,12.914264,11.003669,12.972793,17.431668,23.369746,12.352058,17.433809,30.327968,...,12.310972,13.022394,26.469003,13.029198,23.371292,26.902328,NaN,13.022394,11.001753,23.351058
restaurant_longitude,75.892471,77.683237,77.6784,76.976494,80.249982,78.408321,85.33982,76.60665,78.386744,78.046106,...,76.659264,80.242439,80.316344,77.570997,85.327872,75.794257,NaN,80.242439,76.986241,85.325731
delivery_latitude,22.765049,13.043041,12.924264,11.053669,13.012793,17.461668,23.479746,12.482058,17.563809,30.397968,...,12.440972,13.042394,26.539003,13.059198,23.481292,26.912328,NaN,13.052394,11.041753,23.431058
delivery_longitude,75.912471,77.813237,77.6884,77.026494,80.289982,78.438321,85.44982,76.73665,78.516744,78.116106,...,76.789264,80.262439,80.386344,77.600997,85.437872,75.804257,NaN,80.272439,77.026241,85.405731
order_date,2022-03-19,2022-03-25,2022-03-19,2022-04-05,2022-03-26,2022-03-11,2022-03-04,2022-03-14,2022-03-20,2022-02-12,...,2022-03-18,2022-04-05,2022-02-14,2022-03-30,2022-03-08,2022-03-24,2022-02-16,2022-03-11,2022-03-07,2022-03-02
weather,sunny,stormy,sandstorms,sunny,cloudy,cloudy,fog,cloudy,stormy,fog,...,sunny,sandstorms,cloudy,sandstorms,windy,windy,windy,cloudy,cloudy,fog
traffic,high,jam,low,medium,high,jam,jam,medium,jam,jam,...,jam,low,medium,jam,jam,high,jam,low,high,medium
vehicle_condition,2,2,0,0,1,0,1,2,0,2,...,2,2,1,1,2,1,0,1,0,2
type_of_order,snack,snack,drinks,buffet,snack,buffet,meal,meal,buffet,snack,...,drinks,drinks,snack,meal,drinks,meal,buffet,drinks,snack,snack
type_of_vehicle,motorcycle,scooter,motorcycle,motorcycle,scooter,motorcycle,scooter,motorcycle,motorcycle,motorcycle,...,electric_scooter,electric_scooter,motorcycle,scooter,motorcycle,motorcycle,motorcycle,scooter,motorcycle,scooter
multiple_deliveries,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,...,1.0,0.0,2.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0
festival,no,no,no,no,no,no,no,no,no,no,...,no,no,yes,no,no,no,no,no,no,no
city_type,urban,metropolitian,urban,metropolitian,metropolitian,urban,metropolitian,metropolitian,metropolitian,metropolitian,...,urban,metropolitian,metropolitian,metropolitian,metropolitian,metropolitian,metropolitian,metropolitian,metropolitian,metropolitian
time_taken,24,33,26,21,30,26,40,32,34,46,...,29,20,42,29,33,32,36,16,26,36
city_name,INDO,BANG,BANG,COIMB,CHEN,HYD,RANCHI,MYS,HYD,DEH,...,MYS,CHEN,KNP,BANG,RANCHI,JAP,AGR,CHEN,COIMB,RANCHI
order_day,19,25,19,5,26,11,4,14,20,12,...,18,5,14,30,8,24,16,11,7,2
order_month,3,3,3,4,3,3,3,3,3,2,...,3,4,2,3,3,3,2,3,3,3
order_day_of_week,saturday,friday,saturday,tuesday,saturday,friday,friday,monday,sunday,saturday,...,friday,tuesday,monday,wednesday,tuesday,thursday,wednesday,friday,monday,wednesday
is_weekend,1,0,1,0,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
pickup_time_minutes,15.0,5.0,15.0,10.0,15.0,10.0,15.0,5.0,10.0,15.0,...,10.0,15.0,15.0,5.0,10.0,10.0,15.0,15.0,5.0,5.0
order_time_hour,11.0,19.0,8.0,18.0,13.0,21.0,19.0,17.0,20.0,21.0,...,21.0,9.0,18.0,21.0,21.0,11.0,19.0,23.0,13.0,17.0
order_time_of_day,morning,evening,morning,evening,afternoon,night,evening,evening,night,night,...,night,morning,evening,night,night,morning,evening,night,afternoon,evening
distance,3.025149,20.18353,1.552758,7.790401,6.210138,4.610365,16.600361,20.205253,19.97552,10.280582,...,20.206808,3.104827,10.445325,4.657133,16.600272,1.489846,NaN,4.657195,6.232393,12.074396

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45502 entries, 0 to 45501
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rider_id              45502 non-null  str
 1   age                   43648 non-null  float64
 2   ratings               43594 non-null  float64
 3   restaurant_latitude   41872 non-null  float64
 4   restaurant_longitude  41872 non-null  float64
 5   delivery_latitude     41872 non-null  float64
 6   delivery_longitude    41872 non-null  float64
 7   order_date            45502 non-null  str
 8   weather               44977 non-null  str
 9   traffic               44992 non-null  str
 10  vehicle_condition     45502 non-null  int64
 11  type_of_order         45502 non-null  str
 12  type_of_vehicle       45502 non-null  str
 13  multiple_deliveries   44509 non-null  float64
 14  festival              45274 non-null  str
 15  city_type             44304 non-null  str
 16  time_taken            45502 non-null  int64
 17  city_name             45502 non-null  str
 18  order_day             45502 non-null  int64
 19  order_month           45502 non-null  int64
 20  order_day_of_week     45502 non-null  str
 21  is_weekend            45502 non-null  int64
 22  pickup_time_minutes   43862 non-null  float64
 23  order_time_hour       43862 non-null  float64
 24  order_time_of_day     45502 non-null  str
 25  distance              41872 non-null  float64
dtypes: float64(10), int64(5), str(11)
memory usage: 12.5 MB

In [6]:
df.isna().sum()

rider_id                   0
age                     1854
ratings                 1908
restaurant_latitude     3630
restaurant_longitude    3630
delivery_latitude       3630
delivery_longitude      3630
order_date                 0
weather                  525
traffic                  510
vehicle_condition          0
type_of_order              0
type_of_vehicle            0
multiple_deliveries      993
festival                 228
city_type               1198
time_taken                 0
city_name                  0
order_day                  0
order_month                0
order_day_of_week          0
is_weekend                 0
pickup_time_minutes     1640
order_time_hour         1640
order_time_of_day          0
distance                3630
dtype: int64

# dropping irrelevent columns

In [7]:
df.columns

Index(['rider_id', 'age', 'ratings', 'restaurant_latitude',
       'restaurant_longitude', 'delivery_latitude', 'delivery_longitude',
       'order_date', 'weather', 'traffic', 'vehicle_condition',
       'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival',
       'city_type', 'time_taken', 'city_name', 'order_day', 'order_month',
       'order_day_of_week', 'is_weekend', 'pickup_time_minutes',
       'order_time_hour', 'order_time_of_day', 'distance'],
      dtype='str')

In [8]:
df = df.drop(columns=['rider_id', 'order_date', 'restaurant_latitude', 'restaurant_longitude', 'delivery_latitude', 'delivery_longitude'])

In [9]:
df.head()

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,BANG,25,3,friday,0,5.0,19.0,evening,20.183530
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138

# handling missing values

In [10]:
from sklearn.impute import SimpleImputer

In [13]:
age_impute=SimpleImputer(strategy='median')
df[['age']]=age_impute.fit_transform(df[['age']])

In [14]:
rating_impute=SimpleImputer(strategy='median')
df[['ratings']]=rating_impute.fit_transform(df[['ratings']])

In [15]:
weather_impute=SimpleImputer(strategy="most_frequent")
df[["weather"]]=weather_impute.fit_transform(df[["weather"]])

In [16]:
traffic_impute=SimpleImputer(strategy="most_frequent")
df[["traffic"]]=traffic_impute.fit_transform(df[["traffic"]])

In [17]:
mul_del_impute=SimpleImputer(strategy="median")
df[["multiple_deliveries"]]=mul_del_impute.fit_transform(df[["multiple_deliveries"]])

In [18]:
festival_impute=SimpleImputer(strategy="most_frequent")
df[["festival"]]=festival_impute.fit_transform(df[["festival"]])

In [19]:
citytype_impute=SimpleImputer(strategy="most_frequent")
df[["city_type"]]=citytype_impute.fit_transform(df[["city_type"]])

In [20]:
pick_time_impute=SimpleImputer(strategy="median")
df[["pickup_time_minutes"]]=pick_time_impute.fit_transform(df[["pickup_time_minutes"]])

In [21]:
ord_time_impute=SimpleImputer(strategy="median")
df[["order_time_hour"]]=ord_time_impute.fit_transform(df[['order_time_hour']])

In [22]:
distance_impute=SimpleImputer(strategy="median")
df[["distance"]]=distance_impute.fit_transform(df[['distance']])

In [23]:
df.isna().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
time_taken             0
city_name              0
order_day              0
order_month            0
order_day_of_week      0
is_weekend             0
pickup_time_minutes    0
order_time_hour        0
order_time_of_day      0
distance               0
dtype: int64

# encoding

In [24]:
#nominal
nominal=['weather','type_of_order','type_of_vehicle','festival','city_type','city_name','order_day_of_week','order_time_of_day']
nominal

['weather',
 'type_of_order',
 'type_of_vehicle',
 'festival',
 'city_type',
 'city_name',
 'order_day_of_week',
 'order_time_of_day']

In [25]:
ordinal=['traffic']
ordinal
traffic_order=["low","medium","high","jam"]

In [26]:
#numerical
numerical=['age','ratings','vehicle_condition','multiple_deliveries','order_day','order_month','is_weekend',
           'pickup_time_minutes','order_time_hour','distance']
numerical

['age',
 'ratings',
 'vehicle_condition',
 'multiple_deliveries',
 'order_day',
 'order_month',
 'is_weekend',
 'pickup_time_minutes',
 'order_time_hour',
 'distance']

In [27]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [28]:
ohe=OneHotEncoder()
df['weather']=ohe.fit_transform(df[['weather']]).todense()
df['type_of_order']=ohe.fit_transform(df[['type_of_order']]).todense()
df['type_of_vehicle']=ohe.fit_transform(df[['type_of_vehicle']]).todense()
df['festival']=ohe.fit_transform(df[['festival']]).todense()
df['city_type']=ohe.fit_transform(df[['city_type']]).todense()
df['city_name']=ohe.fit_transform(df[['city_name']]).todense()
df['order_day_of_week']=ohe.fit_transform(df[['order_day_of_week']]).todense()
df['order_time_of_day']=ohe.fit_transform(df[['order_time_of_day']]).todense()

In [29]:
df["traffic"].unique()

<ArrowStringArray>
['high', 'jam', 'low', 'medium']
Length: 4, dtype: str

In [30]:
ordinal=['traffic']
traffic_order=[["low","medium","high","jam"]]
ordinal_encoded=OrdinalEncoder(categories=traffic_order)
df["traffic"]=ordinal_encoded.fit_transform(df[["traffic"]])

In [31]:
df

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,37.0,4.9,0.0,2.0,2,0.0,0.0,0.0,1.0,0.0,24,0.0,19,3,0.0,1,15.0,11.0,0.0,3.025149
1,34.0,4.5,0.0,3.0,2,0.0,0.0,1.0,1.0,1.0,33,0.0,25,3,1.0,0,5.0,19.0,0.0,20.183530
2,23.0,4.4,0.0,0.0,0,0.0,0.0,1.0,1.0,0.0,26,0.0,19,3,0.0,1,15.0,8.0,0.0,1.552758
3,38.0,4.7,0.0,1.0,0,1.0,0.0,1.0,1.0,1.0,21,0.0,5,4,0.0,0,10.0,18.0,0.0,7.790401
4,32.0,4.6,1.0,2.0,1,0.0,0.0,1.0,1.0,1.0,30,0.0,26,3,0.0,1,15.0,13.0,0.0,6.210138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45497,30.0,4.8,0.0,2.0,1,0.0,0.0,0.0,1.0,1.0,32,0.0,24,3,0.0,0,10.0,11.0,0.0,1.489846
45498,21.0,4.6,0.0,3.0,0,1.0,0.0,1.0,1.0,1.0,36,1.0,16,2,0.0,0,15.0,19.0,0.0,9.193014
45499,30.0,4.9,1.0,0.0,1,0.0,0.0,0.0,1.0,1.0,16,0.0,11,3,1.0,0,15.0,23.0,0.0,4.657195
45500,20.0,4.7,1.0,2.0,0,0.0,0.0,1.0,1.0,1.0,26,0.0,7,3,0.0,0,5.0,13.0,0.0,6.232393
45501,23.0,4.9,0.0,1.0,2,0.0,0.0,1.0,1.0,1.0,36,0.0,2,3,0.0,0,5.0,17.0,0.0,12.074396

# outliers handling

In [32]:
from feature_engine.outliers import Winsorizer
w=Winsorizer(capping_method='gaussian',tail="both")
df[numerical]=w.fit_transform(df[numerical])

# scaling

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
numerical

['age',
 'ratings',
 'vehicle_condition',
 'multiple_deliveries',
 'order_day',
 'order_month',
 'is_weekend',
 'pickup_time_minutes',
 'order_time_hour',
 'distance']

In [36]:
binary_cols=["is_weekend"]
ss=StandardScaler()
df[numerical]=ss.fit_transform(df[numerical])

In [37]:
df.head()

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,1.316001,0.900092,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.174055,24,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,-1.351522
1,0.784417,-0.502673,0.0,0.0,0.0,1.0,0.0,0.0,3.0,1.174055,33,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.459798
2,-1.164726,-0.853365,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.220523,26,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.459798
3,1.493196,0.198709,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.220523,21,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.459798
4,0.430027,-0.151982,1.0,0.0,0.0,0.0,0.0,0.0,2.0,-0.023234,30,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.459798

# Normalization

In [38]:
from sklearn.preprocessing import PowerTransformer

In [39]:
pf=PowerTransformer(method="yeo-johnson")
df[numerical]=pf.fit_transform(df[numerical])

In [40]:
df.head()

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,1.322766,1.081305,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.166915,24,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,-1.319034
1,0.781627,-0.757214,0.0,0.0,0.0,1.0,0.0,0.0,3.0,1.166915,33,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.430938
2,-1.161369,-1.018743,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.231436,26,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.430938
3,1.503872,-0.038351,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.231436,21,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.430938
4,0.423033,-0.441176,1.0,0.0,0.0,0.0,0.0,0.0,2.0,-0.003168,30,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.430938

In [41]:
x=df.drop(columns="time_taken")
y=df["time_taken"]

In [42]:
x.isna().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
city_name              0
order_day              0
order_month            0
order_day_of_week      0
is_weekend             0
pickup_time_minutes    0
order_time_hour        0
order_time_of_day      0
distance               0
dtype: int64

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

# Linear regression

In [47]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,root_mean_squared_error,r2_score

In [49]:
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 42.22611697174039
root_mean_squared_error 6.498162584280297
R2 score 0.5250705017312793

# KNN

In [50]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score

In [51]:
knn=LinearRegression()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 42.22611697174039
root_mean_squared_error 6.498162584280297
R2 score 0.5250705017312793

# Decision TreeRegressor

In [52]:
from sklearn.tree import DecisionTreeRegressor

In [53]:
dt=DecisionTreeRegressor()
dt.fit(x_train,y_train)
y_pred = dt.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 53.90209867047577
root_mean_squared_error 7.341804864641649
R2 score 0.3937473177007348

# XGBoost

In [58]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score

In [59]:
xgb=XGBRegressor(n_estimators=100,
                          learning_rate=0.089,
                          max_depth=8,
                          Algorithm__subsample=0.95,
                           random_state=23)
xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

C:\Users\ACS\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [15:07:00] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:793:
Parameters: { "Algorithm__subsample" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

mean_squared_error 26.4791316986084
root_mean_squared_error 5.145787715911865
R2 score 0.7021814584732056

# cross validation

In [60]:
from sklearn.model_selection import KFold,cross_val_score

In [61]:
kfcv=KFold(n_splits=5,shuffle=True,random_state=23)
cross_val_score(estimator=xgb,
               X=x,
               y=y,
               scoring='r2',
               cv=kfcv,
               n_jobs=-1).mean()

np.float64(0.6971478819847107)

In [62]:
import pandas as pd
test_data = [{
    'age': 25, 
    'ratings': 5.0, 
    'weather': 'cloudy', 
    'traffic': 'jam', 
    'vehicle_condition': 1, 
    'type_of_order': 'meal', 
    'type_of_vehicle': 'motorcycle', 
    'multiple_deliveries': 3, 
    'festival': 'no', 
    'city_type': 'urban', 
    'city_name': 'BANG', 
    'order_day': 13, 
    'order_month': 6, 
    'order_day_of_week': 'saturday', 
    'is_weekend': 1, 
    'pickup_time_minutes': 10,       
    'order_time_hour': 18, 
    'order_time_of_day': 'evening', 
    'distance': 5.5
}]

df_input = pd.DataFrame(test_data)

categorical_cols = [
    'weather', 'traffic', 'type_of_order', 'type_of_vehicle', 
    'festival', 'city_type', 'city_name', 'order_day_of_week', 'order_time_of_day'
]

for col in categorical_cols:
    df_input[col] = df_input[col].astype('category')

prediction = xgb.predict(df_input)

print(f"Predicted Delivery Time: {prediction[0]:.2f} minutes")

Predicted Delivery Time: 39.22 minutes